name: Unit Test

# on events
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

# jobs to run
jobs:
  # job 1
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout the repository
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instal dependencies
        run: npm ci

      - name: npm test
        run: npm test
